### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by theoneandonly-1** [SokoloffA/radiola#3]
Really loving the simplicity of this app, makes switching between a list of 20 stations super easy! 

Would it be possible to add functionality to re-order the list of stations? Wherever the cursor is placed at the moment, it adds a new station under that entry (of which I've got them in such a random order now); granted I could just re-add them all, but some others might appreciate this if its not too much effort :) 

&& would it be possible to add grouping to stations? For example, NTS Radio has two streams + lots of infinite mixes that I would like to have under the one NTS label. Unsure if its possible when you hover over it, it opens a second menubar list to the left/right of that label.

**Comment by SokoloffA** [comment]
> Would it be possible to add functionality to re-order the list of stations?

Yes, and even more has already been done in the developer version. You will be able to drag and drop rows.  Also I redesigned the stations window. 
![stations](https://user-images.githubusercontent.com/854935/181075003-9d49267f-5c4e-4775-92f6-29602524fb38.png)

Added a history window.

Now I want to add automatic updates. And I will be releasing a new version of the program. Please be patient a little, I hope the new version will please you

...
> would it be possible to add grouping to stations

In general, menus with submenus are inconvenient. I'll think about what I can do.

**Comment by theoneandonly-1** [comment]
> > Would it be possible to add functionality to re-order the list of stations?
> 
> Yes, and even more has already been done in the developer version. You will be able to drag and drop rows. Also I redesigned the stations window. ![stations](https://user-images.githubusercontent.com/854935/181075003-9d49267f-5c4e-4775-92f6-29602524fb38.png)
> 
> Added a history window.
> 
> Now I want to add automatic updates. And I will be releasing a new version of the program. Please be patient a little, I hope the new version will please you
> 
> ...
> 
> > would it be possible to add grouping to stations
> 
> In general, menus with submenus are inconvenient. I'll think about what I can do.

Yes. This looks great, can't wait to try out the new release :)

**Comment by SokoloffA** [comment]
Hi! I have released a [new version of the Radiola](https://github.com/SokoloffA/radiola/releases/tag/v3.0), as I wrote it supports drag and drop for stations. 
I plan to add station grouping in future releases.

**Comment by josecarre** [comment]
Hi @SokoloffA 

As we still have this open thread for features suggestion/request... App is really great, but it would be possible to add a volume adjuster in thr bar menu? maybe between current song and stations list? something like this or where you think it fits better :)
![image](https://user-images.githubusercontent.com/10371413/201639475-cf58698c-2cc6-4d6b-9fae-500cff51a866.png)

**Comment by josecarre** [comment]
Hi, thanks for your reply. I think that no matter the size we should maintain the list of favourite stations in the menu of the micro window, right? I only miss the volume thing, but I wouldn;t remove anything :), the menu as it's right now is just great!
Audio device maybe is something that can be in app window, and not mini window. But sometimes is helpful to have radio in a device that is not the overall one selected in macos.

**Comment by theoneandonly-1** [comment]
> > it would be possible to add a volume adjuster in the bar menu?
> 
> I think maybe it makes sense to replace the menu with a micro window like:
> 
> ![Снимок экрана 2022-11-15 в 09 46 20](https://user-images.githubusercontent.com/854935/201848450-0399769f-cf09-4965-9fa9-ac3ad928912b.png) or ![Снимок экрана 2022-11-15 в 09 45 50](https://user-images.githubusercontent.com/854935/201848527-2f866673-f556-4830-aa71-f44e370cf8e4.png)
> 
> > And maybe a small menu to choose output audio device, for fast switching.
> 
> I'll see if I can add a list of devices to the preferences dialog.
> 
> P.S. I have added the ability to group stations. If you are interested, I will make a beta release in the coming days, and I will send you a link.

Looking forward to the beta with grouping, thanks for all your hard work.

**Comment by SokoloffA** [comment]
So, I made a [beta version](https://github.com/SokoloffA/radiola/releases/download/v3.99.1/Radiola-3.99.1.dmg). Only one visible change is the grouping of stations. 

Groups have appeared, so the file format has changed. The old file should load without problems (I have checked many times), but just in case, make a backup before launching a beta version. Launch the terminal and enter the following command:
```
cp ~"/Library/Containers/com.github.SokoloffA.Radiola/Data/Library/Application Support/com.github.SokoloffA.Radiola/bookmarks.opml" radiola-bookmarks.opl
```
   
   
Feel free to tell me about any problems.

**Comment by SokoloffA** [comment]
Hi! I have implemented all your wishes. You can try them in [beta version 3.99.2](https://github.com/SokoloffA/radiola/releases/tag/v3.99.2). If there are no critical problems, I will release 4.0 in a few days.

**Comment by josecarre** [comment]
Hi @SokoloffA , thanks for this update with all our asks :), but when trying to update via the "check update button" it downloads the package and then shows this:
![image](https://user-images.githubusercontent.com/10371413/208468658-61d02b25-de25-4bec-bbea-0b7410f225fd.png)
Any way to fix? or should i just uninstall and install? not sure if anyone else got this error. Im running Monterey (12.6.1)

**Comment by josecarre** [comment]
> Hi! This is due to the incorrect digital signature of the program. Through my fault, version 3.X has an incorrect signature. I fixed it in 4.0. But now 3.X and 4.0 have different signatures and cannot be updated automatically.
> 
> Just download [dmg](https://github.com/SokoloffA/radiola/releases) and update the program by hands. I hope that after 4.0 there will be no such problems.

Yeah, it worked, but lost all my saved stations when replacing dmg :(. But yes, reinstalling... installs 😆

**Comment by SokoloffA** [comment]
> lost all my saved stations when replacing dmg

OH, SORRY! I hadn't thought of that. Poorly signed applications store data in a separate location. 
But good news! Your data is safe.  
Please exit the program. Copy file 
      ```~/Library/Containers/com.github.SokoloffA.Radiola/Data/Library/Application Support/com.github.SokoloffA.Radiola/bookmarks.opml``` to ```~/Library/Application Support/com.github.SokoloffA.Radiola/bookmarks.opml```. Tilda is your home directory.

P.S.
After installing from dmg, did mac OS tell you that it can't check the program for viruses?

**Comment by josecarre** [comment]
> > lost all my saved stations when replacing dmg
> 
> OH, SORRY! I hadn't thought of that. Poorly signed applications store data in a separate location. But good news! Your data is safe. Please exit the program. Copy file `~/Library/Containers/com.github.SokoloffA.Radiola/Data/Library/Application Support/com.github.SokoloffA.Radiola/bookmarks.opml` to `~/Library/Application Support/com.github.SokoloffA.Radiola/bookmarks.opml`. Tilda is your home directory.
> 
> P.S. After installing from dmg, did mac OS tell you that it can't check the program for viruses?

I just saw this late and re-added manually them, but it was not a long list. But is good to know there is a way just in case other used has same issue... so is good to have it documented here :)

Regarding dmg installation, no msg related with viruses, just the usual unknown sources disclaimer that needs to be cleared from security settings.

**Comment by josecarre** [comment]
As other feature request, because it doesnt seem to be in, or cant find it. Something in preferences to mark a box so that radiola opens on startup in tabbar, silently :)

**Comment by SokoloffA** [comment]
Please explain in more detail what you want. Unfortunately, I didn't understand what you mean by "radiola opens on startup in tabbar, silently ".

**Comment by josecarre** [comment]
> Please explain in more detail what you want. Unfortunately, I didn't understand what you mean by "radiola opens on startup in tabbar, silently ".
> 
> P.S. And also, it will be great if you open a new issue.

Hi, I just mean to have a checkbox in configuration to make Radiola openning on system boot, thats all; as radiola already starts minimized in upper tab :)
But is just an small thing, not very important ;), the app is great
